[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.130.0"
  GO_VERSION = "1.22.5"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"

[[redirects]]
  from = "https://ikutlahaku.netlify.app/*"
  to = "https://ikutlahaku.hkbprawamangun.com/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
