[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.145.0"
  GO_VERSION = "1.24.1"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  TZ = "Asia/Jakarta"

[[redirects]]
  from = "https://ikutlahaku.netlify.app/*"
  to = "https://www.ikutlahaku.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ikutlahaku.hkbprawamangun.com/*"
  to = "https://www.ikutlahaku.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ikutlahaku.andremoreno.id/*"
  to = "https://www.ikutlahaku.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
