[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.133.0"
  GO_VERSION = "1.23.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"

[[redirects]]
  from = "https://ikutlahaku.netlify.app/*"
  to = "https://www.ikutlahaku.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ikutlahaku.hkbprawamangun.com/*"
  to = "https://www.ikutlahaku.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://ikutlahaku.andremoreno.id/*"
  to = "https://www.ikutlahaku.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
