[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.104.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"


[[redirects]]
  from = "https://ikutlahaku.hkbp.tech/*"
  to = "https://ikutlahaku.andremoreno.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://ikutlahaku.netlify.app/*"
  to = "https://ikutlahaku.andremoreno.com/:splat"
  status = 301
  force = true


[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404